# Site settings
title: Jane Bailey
email: jane@janebaileybooks.com
description: > # this means to ignore newlines until "baseurl:"
  Jane Bailey is a self-published speculative fiction writer; here you can find information about her published books,
  upcoming releases, and appearances. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.janebaileybooks.com" # the base hostname & protocol for your site
twitter_username: janebaileybooks

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass
    
    
exclude: [vendor, script]