name: Jekyll site CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: jekyll build
      uses: mbursi/jekyll-build-only-action@v1.0.0
   # - name: HTMLProofer
   #   uses: chabad360/htmlproofer@v2
   #   with:
        # The directory to scan
   #     directory: "./_site"
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.SSH_HOST }}
        if_key_exists: fail
    - name: rsync deployment
      # You may pin to the exact commit or the version.
      # uses: D3rHase/rsync-deploy-action@5af3ec7ad17529c7c223819f54fe0d5cad1357e1
      uses: D3rHase/rsync-deploy-action@v0.2
      with:
        # hostname / IP of the server
        HOST: 167.71.175.126
        # ssh port of the server
        PORT: 22
        # user of the server
        USER: agni
        # private ssh key registered on the server
        PRIVATE_SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        # path of the file-s to deploy
        REPOSITORY_PATH: ./_site
        # server path / destination
        SERVER_PATH: /var/www/janebaileybooks.com/
